# Generated by Django 3.0.6 on 2020-06-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_recipe_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unity', models.CharField(choices=[('gr', 'grammes'), ('kg', 'kilogrammes'), ('l', 'litres'), ('cl', 'centilitres'), ('ml', 'millilitres')], default='gr', max_length=15)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='content.IngredientLine', to='content.Ingredient'),
        ),
    ]
