# Generated by Django 3.0.6 on 2020-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200602_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientline',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
