# Generated by Django 3.0.6 on 2020-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200606_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientline',
            name='unity',
            field=models.CharField(choices=[('gr', 'grammes'), ('kg', 'kilogrammes'), ('l', 'litres'), ('cl', 'centilitres'), ('ml', 'millilitres'), ('', '')], default='gr', max_length=15),
        ),
    ]
